In [7]:
import numpy as np

In [8]:
mylist = [1,2,3,4,5]

In [9]:
mylist

[1, 2, 3, 4, 5]

In [10]:
type(mylist)

list

In [11]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [32]:
mylist = [[1,23,43,565,7,87],[123,4,5,6,56,5]]

In [33]:
mylist

[[1, 23, 43, 565, 7, 87], [123, 4, 5, 6, 56, 5]]

In [34]:
new_array = np.array(mylist)

In [35]:
new_array

array([[  1,  23,  43, 565,   7,  87],
       [123,   4,   5,   6,  56,   5]])

In [36]:
np.zeros(2)

array([0., 0.])

In [37]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

diag() returns given elements as diagonal matrix with numbers as given in input

In [47]:
np.diag((12,3,4,34,5,4,55,7,768,78,78,78))

array([[ 12,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   4,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  34,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   5,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   4,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  55,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   7,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 768,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  78,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  78,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  78]])

linspace() returns the evenly spaced numbers given starting and ending numbers

In [58]:
np.linspace(1,100,2)

array([  1., 100.])

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

eye() refers to as an identity matrix 

In [60]:
np.eye(99)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

seed value returns the array of random numbers as constant as long we use this particular number as seed 

In [69]:
np.random.seed(99)
np.random.randint(0,1000,100)

array([641,  35, 185, 168, 713, 744, 722,  68, 197, 948, 385, 919, 254,
       803,  55, 449, 176, 221,  59, 998, 363, 244, 215, 642, 192, 652,
       424, 968,  20, 505,  59, 807, 591, 762,  47, 795, 830, 741, 750,
       740, 492, 761,  62, 529,  73, 160, 277, 239, 169, 867, 531, 790,
       922, 690, 955, 773, 652, 352, 764, 949, 731, 257, 428, 843, 114,
        11, 733,  95, 881, 297, 123, 929, 268,  77, 460, 483,  88, 488,
       457, 626, 505, 779,   0, 663, 445, 523, 739, 114, 496, 422, 381,
       450, 315, 490,  83, 658,  60, 104, 795, 634])

In [70]:
np.random.randint(0,1000,100)

array([419, 621, 181,  29, 661, 617, 108, 740, 929,  45, 349, 447, 446,
       543, 587, 862, 779, 748, 868,  41, 855, 694, 990, 827, 859, 229,
       535, 298, 347, 165, 160, 899, 391, 284, 941, 187, 325, 941, 423,
       823, 184, 376, 688, 334,  34, 355, 564, 672, 744, 795, 320, 590,
       361, 314, 928, 376, 740, 475, 657,  13, 240, 695, 537, 882, 394,
       159, 922, 503, 534, 650, 620, 353, 884, 242,  38, 760, 402, 589,
       731, 189, 254, 130,  39, 738, 643, 591, 255,  94, 157, 842, 546,
       218, 966, 417, 139, 862, 958, 838, 655, 127])

In [71]:
np.random.rand(2,2)

array([[0.52658634, 0.25629263],
       [0.99536488, 0.10662337]])

In [72]:
np.random.randn(5,5)

array([[-1.13322409, -0.27908571,  1.3966199 ,  0.03221944, -2.61366077],
       [-1.00157763, -0.56751101, -0.22565803,  0.93802381,  0.83678413],
       [ 0.81214848,  0.23230697, -0.29510767, -0.361676  ,  0.43211507],
       [ 0.93395855,  1.55263386,  0.09362341,  0.29482583,  1.48543077],
       [-1.08688515,  0.82116281, -0.7879492 ,  1.59381165,  1.40590436]])

randn from random returns the random number in whatever dimension requested 

In [73]:
np.random.randn(3,4)

array([[ 1.64475657,  1.54159871,  0.84060764, -1.0230944 ],
       [ 0.4947723 ,  0.8957326 ,  0.47735201, -0.11453052],
       [ 0.15689743,  0.38759667, -1.02622658,  0.6791429 ]])

random module returns random numbers, here in randint returns the random number between start and stop
in whatever dimensions it is promted

In [79]:
np.random.randint(1,2343,(2,4))

array([[2304, 1064, 1558,  812],
       [1049, 1468, 1131,  461]])

In [80]:
import pandas as pd

In [81]:
new = [123,32,3,2,3,2,2,3]

In [86]:
np.random.seed(90)
mydata = np.random.randint(0,100,(3,3))

In [84]:
myindex = ['A','B','C']

In [85]:
mycolumns = ['x','y','z']

In [87]:
mydata

array([[91, 29, 31],
       [67, 39, 68],
       [58, 37, 18]])

In [93]:
df = pd.DataFrame(mydata,index=myindex,columns = mycolumns)

In [94]:
df

x   y   z
A  91  29  31
B  67  39  68
C  58  37  18

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       3 non-null      int32
 1   y       3 non-null      int32
 2   z       3 non-null      int32
dtypes: int32(3)
memory usage: 60.0+ bytes


In [96]:
pwd

'C:\\Users\\user'

In [97]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 1AEA-2BBE

 Directory of C:\Users\user

08/07/2024  05:00 PM    <DIR>          .
08/07/2024  05:00 PM    <DIR>          ..
08/12/2021  11:50 AM    <DIR>          .Altair
01/30/2024  07:58 AM    <DIR>          .anaconda
11/11/2022  07:41 PM    <DIR>          .atom
05/04/2021  02:59 PM               199 .bash_profile
08/07/2024  05:00 PM    <DIR>          .conda
02/01/2024  07:59 AM                60 .condarc
01/30/2024  07:57 AM    <DIR>          .continuum
07/22/2024  10:09 AM                62 .gitconfig
12/20/2020  11:31 AM    <DIR>          .idlerc
08/07/2024  02:56 PM    <DIR>          .ipynb_checkpoints
05/04/2021  05:23 PM    <DIR>          .ipython
01/31/2024  06:48 PM    <DIR>          .jupyter
05/05/2021  09:28 PM    <DIR>          .keras
05/06/2021  06:54 AM    <DIR>          .matplotlib
08/03/2023  12:11 AM    <DIR>          .micromamba
05/04/2021  05:18 PM                75 .python_history
05/06/2021  06:53 AM    <DI

'0' is not recognized as an internal or external command,
operable program or batch file.


In [100]:
df = pd.read_csv('tips.csv')

In [101]:
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [113]:
pwd

'C:\\Users\\user'

In [120]:
df2 = pd.read_csv('C:\\Users\\user\\Downloads\\UNZIP_FOR_NOTEBOOKS_FINAL\\03-Pandas\\newfile.csv')

In [121]:
df2

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [122]:
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [123]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [124]:
df.head(20)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0        16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1        10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2        21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3        23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4        24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5        25.29  4.71    Male     No  Sun  Dinner     4              6.32   
6         8.77  2.00    Male     No  Sun  Dinner     2              4.38   
7        26.88  3.12    Male     No  Sun  Dinner     4              6.72   
8        15.04  1.96    Male     No  Sun  Dinner     2              7.52   
9        14.78  3.23    Male     No  Sun  Dinner     2              7.39   
10       10.27  1.71    Male     No  Sun  Dinner     2              5.14   
11       35.26  5.00  Female     No  Sun  Dinner     4              8.82   
12       15.42  1.57    Male     No  Sun  Dinner     2              7.71   
13       18.43  3.00    Male     No  Sun  Dinner     4              4.61   
14       14.83  3.02  Female     No  Sun  Dinner     2              7.42   
15       21.58  3.92    Male     No  Sun  Dinner     2             10.79   
16       10.33  1.67  Female     No  Sun  Dinner     3              3.44   
17       16.29  3.71    Male     No  Sun  Dinner     3              5.43   
18       16.97  3.50  Female     No  Sun  Dinner     3              5.66   
19       20.65  3.35    Male     No  Sat  Dinner     3              6.88   

            Payer Name         CC Number Payment ID  
0   Christy Cunningham  3560325168603410    Sun2959  
1       Douglas Tucker  4478071379779230    Sun4608  
2       Travis Walters  6011812112971322    Sun4458  
3     Nathaniel Harris  4676137647685994    Sun5260  
4         Tonya Carter  4832732618637221    Sun2251  
5           Erik Smith   213140353657882    Sun9679  
6   Kristopher Johnson  2223727524230344    Sun5985  
7          Robert Buck  3514785077705092    Sun8157  
8      Joseph Mcdonald  3522866365840377    Sun6820  
9        Jerome Abbott  3532124519049786    Sun3775  
10       William Riley      566287581219    Sun2546  
11        Diane Macias  4577817359320969    Sun6686  
12     Chad Harrington      577040572932    Sun1300  
13        Joshua Jones  6011163105616890    Sun2971  
14       Vanessa Jones    30016702287574    Sun3848  
15      Matthew Reilly   180073029785069    Sun1878  
16    Elizabeth Foster  4240025044626033    Sun9715  
17        John Pittman  6521340257218708    Sun2998  
18      Laura Martinez    30422275171379    Sun2789  
19       Timothy Oneal  6568069240986485    Sat9213

In [129]:
df[df['total_bill'] > 40]

total_bill    tip     sex smoker   day    time  size  price_per_person  \
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07   
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04   
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77   
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03   
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94   
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27   
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78   
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08   

          Payer Name         CC Number Payment ID  
59       Brian Ortiz  6596453823950595    Sat8139  
95     Aaron Bentley   180026611638690    Fri9628  
102    Heather Cohen   379771118886604    Sat6240  
142     Eric Andrews  4356531761046453   Thur3621  
156    Ryan Gonzales  3523151482063321    Sun7518  
170    Gregory Clark  5473850968388236    Sat1954  
182     Jose Parsons  4112207559459910    Sun2337  
184      Stephen Cox  3547798222044029    Sun5140  
197      Brooke Soto  5544902205760175   Thur9313  
212  Alex Williamson      676218815212    Sat4590

In [135]:
df[df['sex'] == 'Male' ]

total_bill   tip   sex smoker  day    time  size  price_per_person  \
1         10.34  1.66  Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50  Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31  Male     No  Sun  Dinner     2             11.84   
5         25.29  4.71  Male     No  Sun  Dinner     4              6.32   
6          8.77  2.00  Male     No  Sun  Dinner     2              4.38   
..          ...   ...   ...    ...  ...     ...   ...               ...   
236       12.60  1.00  Male    Yes  Sat  Dinner     2              6.30   
237       32.83  1.17  Male    Yes  Sat  Dinner     2             16.42   
239       29.03  5.92  Male     No  Sat  Dinner     3              9.68   
241       22.67  2.00  Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75  Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
5            Erik Smith   213140353657882    Sun9679  
6    Kristopher Johnson  2223727524230344    Sun5985  
..                  ...               ...        ...  
236       Matthew Myers  3543676378973965    Sat5032  
237        Thomas Brown  4284722681265508    Sat2929  
239       Michael Avila  5296068606052842    Sat2657  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[157 rows x 11 columns]

In [148]:
df[(df['sex'] == 'Male') & (df['tip'] >5) & (df['size'] >2)]

total_bill    tip   sex smoker   day    time  size  price_per_person  \
23        39.42   7.58  Male     No   Sat  Dinner     4              9.86   
44        30.40   5.60  Male     No   Sun  Dinner     4              7.60   
47        32.40   6.00  Male     No   Sun  Dinner     4              8.10   
59        48.27   6.73  Male     No   Sat  Dinner     4             12.07   
116       29.93   5.07  Male     No   Sun  Dinner     4              7.48   
141       34.30   6.70  Male     No  Thur   Lunch     6              5.72   
170       50.81  10.00  Male    Yes   Sat  Dinner     3             16.94   
183       23.17   6.50  Male    Yes   Sun  Dinner     4              5.79   
211       25.89   5.16  Male    Yes   Sat  Dinner     4              6.47   
212       48.33   9.00  Male     No   Sat  Dinner     4             12.08   
239       29.03   5.92  Male     No   Sat  Dinner     3              9.68   

            Payer Name         CC Number Payment ID  
23      Lance Peterson  3542584061609808     Sat239  
44         Todd Cooper      503846761263    Sun2274  
47        James Barnes  3552002592874186    Sun9677  
59         Brian Ortiz  6596453823950595    Sat8139  
116        Shawn Blake  4689079711213722      Sun22  
141     Steven Carlson  3526515703718508   Thur1025  
170      Gregory Clark  5473850968388236    Sat1954  
183  Dr. Michael James     4718501859162    Sun6059  
211     Christopher Li  6011962464150569    Sat6735  
212    Alex Williamson      676218815212    Sat4590  
239      Michael Avila  5296068606052842    Sat2657

In [153]:
df[df['day'].isin(['Sat','Sun'])]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
..          ...   ...     ...    ...  ...     ...   ...               ...   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
238      Kimberly Crane      676184013727    Sat9777  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[163 rows x 11 columns]